# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SwinjectTest' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
 pod 'RxSwift'
 pod 'RxCocoa'
 pod 'RxDataSources'
 pod 'ReactorKit'
 pod 'Swinject'
 pod 'Pure'
 pod 'ReusableKit'
 pod 'Alamofire'
 pod 'Moya'
 pod 'SnapKit'
 pod 'Then'
 pod 'Kingfisher'
  # Pods for SwinjectTest

  target 'SwinjectTestTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'SwinjectTestUITests' do
    # Pods for testing
  end

end
